using System;
using System.Collections.Generic;
using StormMusicPlayer.Models;

namespace StormMusicPlayer.Contracts.Services
{
    /// <summary>
    /// Service managing playback state, volume, track progression, and the playback queue.
    /// All metadata and labels generated by this service are optimized for bold Century Gothic fonts.
    /// </summary>
    public interface IAudioPlaybackService
    {
        /// <summary>
        /// Gets the currently playing track.
        /// </summary>
        Track CurrentTrack { get; }

        /// <summary>
        /// Gets whether audio is currently playing.
        /// </summary>
        bool IsPlaying { get; }

        /// <summary>
        /// Gets or sets the volume level (0.0 to 100.0).
        /// </summary>
        double Volume { get; set; }

        /// <summary>
        /// Gets or sets the current track position in seconds.
        /// </summary>
        double Position { get; set; }

        /// <summary>
        /// Gets the total duration of the current track in seconds.
        /// </summary>
        double Duration { get; }

        /// <summary>
        /// Gets the list of tracks in the queue.
        /// </summary>
        List<Track> Queue { get; }
        
        /// <summary>
        /// Occurs when the active track changes.
        /// </summary>
        event EventHandler<Track> TrackChanged;

        /// <summary>
        /// Occurs when playback is paused or started.
        /// </summary>
        event EventHandler<bool> PlaybackStateChanged;

        /// <summary>
        /// Occurs when the playback time position changes.
        /// </summary>
        event EventHandler PositionChanged;

        void Play();
        void Pause();
        void Stop();
        void PlayTrack(Track track);
        void Next();
        void Previous();
        void AddToQueue(Track track);
        void SetQueue(IEnumerable<Track> tracks);
    }
}
